# Settings-as-code via Probot settings https://probot.github.io/apps/settings/

rulesets:
  - name: Tags rules
    target: tag
    enforcement: active
    conditions:
      ref_name:
        include:
          - "~ALL"
          - "*"
          - "**"
        exclude: []
    bypass_actors:
      - actor_id: 5
        actor_type: RepositoryRole
        bypass_mode: always
    rules:
      - type: creation
      - type: deletion
      - type: non_fast_forward
      - type: update
      - type: required_linear_history
      - type: required_signatures
